#pragma kernel UpdatePoints
#pragma kernel UpdateSticksGroup
struct Point
{
    float3 position, prevPosition;
    int locked;
};

struct Stick
{
    int pointAIdx, pointBIdx;
    float length;
};

float gravity;
float deltaTime;
int numPoints;
int numSticks;
RWStructuredBuffer<Point> ropePoints;
StructuredBuffer<Stick> ropeSticks;
RWStructuredBuffer<float3> ropePositions;
StructuredBuffer<float3> _Positions;

int firstGroup;


[numthreads(64,1,1)]
void UpdatePoints(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numPoints) return;

    Point p = ropePoints[id.x];
    if (p.locked == 1) return;

    float3 positionBeforeUpdate = p.position;
    p.position += (p.position - p.prevPosition);
    p.position += float3(0, -1, 0) * gravity * deltaTime * deltaTime;
    p.prevPosition = positionBeforeUpdate;

    ropePoints[id.x] = p;
}

[numthreads(64,1,1)]
void UpdateSticksGroup(uint3 id : SV_DispatchThreadID)
{
    int index = 2 * id.x + firstGroup;

    if (index >= numSticks) return;

    Stick s = ropeSticks[index];
    Point a = ropePoints[s.pointAIdx];
    Point b = ropePoints[s.pointBIdx];
    float3 stickCenter = (a.position + b.position) * 0.5f;
    float3 stickDir = normalize(b.position - a.position);

    if(a.locked == 0)
        a.position = stickCenter - stickDir * s.length * 0.5f;
    if(b.locked == 0)
        b.position = stickCenter + stickDir * s.length * 0.5f;

    ropePoints[s.pointAIdx] = a;
    ropePoints[s.pointBIdx] = b;

    ropePositions[s.pointAIdx] = a.position;
    ropePositions[s.pointBIdx] = b.position;
}